name: call_log_example
description: Demonstrates how to use the call_log plugin.
version: 1.0.0+1
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  call_log:
    path: ../
  cupertino_icons: ^1.0.8
  workmanager: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true